language: python

python:
  - "3.6.6"

  # - "2.6"
  # - "2.7"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.5"
  # - "3.7.0"


#Install all dependecies
install:
  - pip install -r requirements.txt

#Run tests
script:
  - python -m pytest --cov
  

after_success:
  - coveralls



